version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5

    working_directory: ~/label-maker
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libgdal-dev
            sudo pip install numpy==1.13.3
            sudo pip install -r requirements.txt
            sudo pip install -r requirements-dev.txt
      - run:
          name: Pylint
          command: pylint ~/label-maker/label_maker --rcfile=~/label-maker/.config/pylintrc
      - run:
          name: Unit Tests
          command: python -m unittest discover -v -s test/unit
      - run:
          name: Start moving integration
          command: |
            sudo pip install .
            python -m unittest discover -v -s test/integration
      - run:
          name: Integration Tests
          command: |
            # object detection integration tests
            mkdir integration-od
            cp -r test/fixtures/integration/tiles integration-od/tiles
            cp test/fixtures/integration/portugal-z17.mbtiles integration-od/
            label-maker labels -d integration-od -c test/fixtures/integration/config.integration.object_detection.json
            python test/verify-labels-od.py
            label-maker package -d integration-od -c test/fixtures/integration/config.integration.object_detection.json
            python test/verify-package-od.py

            # Retest that `label-maker labels` works, but from outside the module directory
            cd ~
            label-maker labels --dest label-maker/integration-cl --config label-maker/test/fixtures/integration/config.integration.json > stdout
            cd ~/label-maker
            python test/verify-labels-cl.py
